// ********RoostGPT********
// Test generated by RoostGPT for test JavaTesting using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
const hyperquest = require('hyperquest');
const bl = require('bl');
const qs = require('querystring');

function addRoute(domain, creds, description, expression, actions, callback) {
  const url = `https://${domain}/routes`;
  const data = qs.stringify({
    description,
    expression,
    action: actions.join(';'),
  });

  const options = {
    auth: `${creds['api-key']}`,
    headers: {
      'content-type': 'application/x-www-form-urlencoded',
    },
  };

  const req = hyperquest.post(url, options);
  req.end(data);
  req.on('response', (res) => {
    res.pipe(bl((err, data) => {
      if (err) {
        callback(err, null);
      } else {
        callback(null, data.toString());
      }
    }));
  });
  req.on('error', (err) => {
    callback(err, null);
  });
}

module.exports = addRoute;
