// ********RoostGPT********
// Test generated by RoostGPT for test JavaTesting using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
// update-aliases.js

function toActions(alias) {
  if (!alias || typeof alias.to === 'undefined') {
    throw new Error('Alias must have a "to" property');
  }

  if (typeof alias.to !== 'string' && !Array.isArray(alias.to)) {
    throw new Error('"to" property must be a string or an array');
  }

  const recipients = Array.isArray(alias.to) ? alias.to : [alias.to];
  const actions = recipients.map((email) => `forward("${email}")`);
  if (actions.length === 0) {
    actions.push('stop()');
  } else {
    actions.push('stop()');
  }

  return actions;
}

module.exports = { toActions };
