// ********RoostGPT********
// Test generated by RoostGPT for test JavaTesting using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
// update-aliases.js
function toExpression(domain, alias) {
  if (!domain || !alias || !alias.from) {
    return `match_recipient("${alias && alias.from ? alias.from : ''}@${domain ? domain : ''}")`;
  }
  return `match_recipient("${alias.from}@${domain}")`;
}

module.exports = { toExpression };
