// ********RoostGPT********
// Test generated by RoostGPT for test JavaTesting using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
jest.mock('./update-aliases', () => {
  const originalModule = jest.requireActual('./update-aliases');
  return {
    __esModule: true, // Use it when dealing with esModules
    ...originalModule,
    listRoutes: jest.fn(),
    addRoute: jest.fn(),
    deleteRoute: jest.fn(),
  };
});
